### PR TITLE
Resprited the Destruction Force's texture.

### PR DESCRIPTION
**Pull request by yitang1**
The crafting materials of the Destruction Force has 6 Enchantments, which do not match the texture appearance of the old version, so I resprited texture and added the missing parts.

### CODE REVIEW

**Review by yitang1 — COMMENTED** [review]
DesolationForce

Readjust.

**Comment by vodavodochka** [comment]
Hi dude, maybe you'd like to collaborate with me, but I don't see the need to change the mod too much because there's a Fargo's dlc coming out that will add these features in the future. If you need my discord "vodavodochka"

**Comment by yitang1** [comment]
> Hi dude, maybe you'd like to collaborate with me, but I don't see the need to change the mod too much because there's a Fargo's dlc coming out that will add these features in the future. If you need my discord "vodavodochka"

Sorry to see your message now. You're right😥, but I don't know when the DLC mod will update the Enchantments of the Calamity. He even hasn't finished making the Eternal Mode of the Calamity Boss AI yet😖. At that time, I really wanted to play games, very eager, so I finally rewrote the code and texture by myself, balanced some values, and then played by myself. Now I have tried to upload it to my respository😂.

**Comment by vodavodochka** [comment]
ok, good luck to you!

**Pull request closed without merging**
